version: '3'

services:
  db:
    image: 'postgres:alpine'

    volumes:
      - ./database:/var/lib/postgresql

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/converter
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery worker -A video_converter --loglevel=debug --concurrency=4
    volumes:
      - .:/converter
    depends_on:
      - db
      - redis
