version: '3'

services:
  db:
    image: 'postgres:11.4'

    volumes:
      - ./database:/var/lib/postgresql
    env_file:
      - .env
  redis:
    image: "redis:5.0.5"

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery worker -A video_converter --loglevel=debug --concurrency=4
    env_file:
      - .env
    depends_on:
      - db
      - redis

